### ISSUE TITLE
NoSuchMethod JCTree in maven install

### ISSUE THREAD

**Issue by philougoatesque** [skytides/FulfillSpigot#7]
Hello, 

wanting to test your spigot and apply 2-3 personal patches (which I probably would have committed)
I got this error when I wanted to install the dependencies with Maven, I got this error, having tried everything I found no solution

[INFO] Reactor Summary:
[INFO] 
[INFO] FulfillSpigot-Parent dev-SNAPSHOT .................. SUCCESS [  0.595 s]
[INFO] FulfillSpigot-API 1.8.8-R0.2-SNAPSHOT .............. SUCCESS [  3.419 s]
[INFO] FulfillSpigot 1.8.8-R0.2-SNAPSHOT .................. FAILURE [  4.804 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.013 s
[INFO] Finished at: 2024-10-12T15:32:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project fulfillspigot: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :fulfillspigot

**Comment by skytides** [comment]
Check your java version it should be java 8

**Comment by philougoatesque** [comment]
That good, sorry !

**Comment by skytides** [comment]
All good
